# Generated by Django 4.2.5 on 2023-10-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_price', models.FloatField()),
                ('status', models.SmallIntegerField(choices=[(0, 'no data'), (1, 'created'), (2, 'pending'), (3, 'processing'), (4, 'shipped'), (5, 'delivered'), (6, 'canceled'), (7, 'refunded')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_id', to='customer.customer')),
            ],
        ),
    ]
